### ISSUE TITLE
TO-DO

### ISSUE THREAD

**Issue by cvillan223** [cvillan223/Creative-Writing-App#1]
# Features to be changed/Implemented
- [ ] Refactor code to have function for web scraping tables
- [ ] Refactor code to have function for web scraping websites without tables
- [ ] Ensure noun uniqueness for every entry
- [ ] Label every 3rd week as a revision week
- [ ] Fix determiners to A or An based on the first letter of a noun/verb
- [ ] Separate nouns based on people, places, and things.

# Features to be considered that require a massive overhaul of the program 
- [ ] Change output to prompts 
- [ ] Get input from text files rather than web scraping 
- [ ] Prompts should be generated via machine learning
